variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - build
  - publish

before_script:
  - export PROJECT_VERSION_MAJOR_MINOR=`cat VERSION`
  - export PROJECT_VERSION=`greycat build-version-full`
  - export PROJECT_VERSION_SIMPLE=`greycat build-version`
  - echo "${PROJECT_VERSION} / ${PROJECT_VERSION_SIMPLE}"

build:
  stage: build
  tags: [ linux ]
  script:
    - ./build.sh
  artifacts:
    when: on_success
    expire_in: '30 days'
    paths:
      - dist

publish:
  stage: publish
  tags: [ linux ]
  when: manual
  script:
    - ./publish.sh
  artifacts:
    expire_in: 1 week
    paths:
      - dist
