image: maven:3.8.7-openjdk-18-slim

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - build
  - publish

before_script:
  - export PROJECT_VERSION=`git2version`
  - export PROJECT_VERSION_SIMPLE=`git2version -s`
  - echo "${PROJECT_VERSION} / ${PROJECT_VERSION_SIMPLE}"

build:
  stage: build
  script:
    - mvn clean package
    - mkdir dist && cp target/sdk-0.0.0.jar dist
  artifacts:
    expire_in: 1 week
    paths:
      - dist