image: maven:3.8.7-openjdk-18-slim

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - build
  - publish

before_script:
  - export PROJECT_VERSION=`./git2version`
  - export PROJECT_VERSION_SIMPLE=`./git2version -s`
  - echo "${PROJECT_VERSION} / ${PROJECT_VERSION_SIMPLE}"

build:
  stage: build
  script:
    #- apt -y update && apt -y install git
    - mvn --batch-mode release:update-versions -DdevelopmentVersion=${PROJECT_VERSION_SIMPLE}
    - mvn clean package
    - mkdir -p dist dist/sdk disk/sdk/java && cp target/sdk-${PROJECT_VERSION_SIMPLE}.jar disk/sdk/java/sdk.jar
  artifacts:
    expire_in: 1 week
    paths:
      - dist