variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - build
  - publish

build:
  stage: build
  image: oci.datathings.com/greycat/crossbuild:4.1.7-master
  script:
    - export PROJECT_VERSION_SIMPLE=`git2version -s`
    - mvn versions:set -DnewVersion=${PROJECT_VERSION_SIMPLE}
    - mvn clean package
    - mkdir -p dist dist/sdk dist/sdk/java && cp target/sdk-${PROJECT_VERSION_SIMPLE}.jar dist/sdk/java/sdk.jar
  artifacts:
    expire_in: 1 week
    paths:
      - dist